<?php

class Admin_Page extends CLinkPager{

    public $maxButtonCount = 5;
    public $nextPageLabel;
    public $prevPageLabel;
    public $firstPageLabel;
    public $lastPageLabel;
    public $selectedPageCssClass = 'active';
    public function init()
    {
        $this->nextPageLabel= '下一页';
        $this->prevPageLabel = '上一页';
        $this->firstPageLabel = '首页';
        $this->lastPageLabel = '末页';
        $this->header = '<div class="row"><div class="col-md-5 col-sm-12"><div class="admin_page_info">共 '.$this->itemCount.' 条，每页 '.$this->pageSize.' 条</div></div><div class="col-md-7 col-sm-12"><div class="admin_page_paginate">';
        $this->footer = '</div></div></div>';
        $this->htmlOptions['class'] = 'pagination';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $buttons=$this->createPageButtons();
        if(empty($buttons))
            return;
        echo $this->header;
        echo CHtml::tag('ul',$this->htmlOptions,implode("\n",$buttons));
        echo $this->footer;
    }

    /**
     * Creates the page buttons.
     * @return array a list of page buttons (in HTML code).
     */
    protected function createPageButtons()
    {
        if(($pageCount=$this->getPageCount())<=1)
            return array();

        list($beginPage,$endPage)=$this->getPageRange();
        $currentPage=$this->getCurrentPage(false); // currentPage is calculated in getPageRange()
        $buttons=array();

        // first page
        if ($this->firstPageLabel !== false) {
            $buttons[]=$this->createPageButton($this->firstPageLabel,0,$this->firstPageCssClass,$currentPage<=0,false);
        }
        // prev page
        if ($this->prevPageLabel !== false) {
            if(($page=$currentPage-1)<0)
                $page=0;
            $buttons[]=$this->createPageButton($this->prevPageLabel,$page,$this->previousPageCssClass,$currentPage<=0,false);
        }

        // internal pages
        for($i=$beginPage;$i<=$endPage;++$i)
            $buttons[]=$this->createPageButton($i+1,$i,$this->internalPageCssClass,false,$i==$currentPage);

        // next page
        if ($this->nextPageLabel !== false) {
            if(($page=$currentPage+1)>=$pageCount-1)
                $page=$pageCount-1;
            $buttons[]=$this->createPageButton($this->nextPageLabel,$page,$this->nextPageCssClass,$currentPage>=$pageCount-1,false);
        }
        // last page
        if ($this->lastPageLabel !== false) {
            $buttons[]=$this->createPageButton($this->lastPageLabel,$pageCount-1,$this->lastPageCssClass,$currentPage>=$pageCount-1,false);
        }

        return $buttons;
    }

}